apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: dev
data:
  # Used by client container to generate .env at runtime
  API_URL: "http://backend-svc:3000/api"
  CLIENT_URL: "http://frontend.dev.svc.cluster.local"
