apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: dev
type: Opaque
stringData:
  # Use private IP/DNS of your Mongo EC2
  MONGO_URI: "mongodb://rmitapp:rmitapp123@172.31.17.36:27017/rmit-store?authSource=rmit-store"
