apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: dev
type: Opaque
stringData:
  JWT_SECRET: "changeme-dev"
  # Use private IP/DNS of your Mongo EC2
  MONGO_URI: "mongodb://rmitapp:rmitapp123@172.31.42.79:27017/rmit-store?authSource=rmit-store"
