apiVersion: batch/v1
kind: Job
metadata:
  name: seed-db
  namespace: dev
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: seed
        image: 293113319402.dkr.ecr.us-east-1.amazonaws.com/rmit-store/backend:latest
        command: ["sh","-lc"]
        args: ["npm run seed:db -- admin@rmit.edu.vn mypassword"]
        env:
        - name: PORT
          value: "3000"
        - name: BASE_API_URL
          value: "api"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGO_URI