apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: prod
type: Opaque
stringData:
  JWT_SECRET: "changeme-prod"
  MONGO_URI: "mongodb://rmitapp:rmitapp123@172.31.42.79:27017/rmit-store?authSource=rmit-store"
