apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: web
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-svc      # ⬅️ sends /api to backend
            port: { number: 3000 }
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-svc     # ⬅️ everything else to frontend
            port: { number: 8080 }
