all:
  children:
    mongodb:
      hosts:
        mongo:
          ansible_aws_ssm_region: us-east-1
          ansible_connection: aws_ssm
          ansible_user: ec2-user
          # Prefer instance-id with SSM (more robust than IP)
          ansible_aws_ssm_instance_id: "{{ lookup('env','MONGODB_INSTANCE_ID') | default(mongodb_instance_id, true) }}"
          ansible_aws_ssm_region: "{{ lookup('env','REGION') | default('us-east-1', true) }}"
